<a href="https://colab.research.google.com/github/YashRaj-37/CODSOFT/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install hmmlearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import entropy
from hmmlearn import hmm
from sklearn.preprocessing import LabelEncoder

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 kB 7.4 MB/s eta 0:00:00


In [10]:
df = pd.read_csv("/content/heart_failure_clinical_records_dataset.csv")
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1


In [9]:
print(df.describe())

              age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.0

In [3]:
print(df.corr()["DEATH_EVENT"].sort_values(ascending=False))

death_prob = df["DEATH_EVENT"].mean()
print(death_prob)

DEATH_EVENT                 1.000000
serum_creatinine            0.294278
age                         0.253729
high_blood_pressure         0.079351
anaemia                     0.066270
creatinine_phosphokinase    0.062728
diabetes                   -0.001943
sex                        -0.004316
smoking                    -0.012623
platelets                  -0.049139
serum_sodium               -0.195204
ejection_fraction          -0.268603
time                       -0.526964
Name: DEATH_EVENT, dtype: float64
0.3210702341137124


In [4]:
joint_prob = len(df[(df["age"] > 60) & (df["DEATH_EVENT"] == 1)]) / len(df)
print(joint_prob)

0.17391304347826086


In [5]:
over60 = df[df["age"] > 60]
cond_prob = over60["DEATH_EVENT"].mean()
print(cond_prob)

0.3795620437956204


In [6]:
mle = df["DEATH_EVENT"].sum() / len(df)
print(mle)
p = 0.32
q = 0.20
kl = p*np.log(p/q) + (1-p)*np.log((1-p)/(1-q))
print(kl)

0.3210702341137124
0.0398882893001483


In [13]:
features = df[["age","creatinine_phosphokinase","serum_creatinine"]].values
model = hmm.GaussianHMM(n_components=3, n_iter=100)
model.fit(features)
hidden_states = model.predict(features)
states = ["Healthy", "At Risk", "Critical"]
results = [states[i] for i in hidden_states]
print(results[:20])
print(model.transmat_)

['Healthy', 'Critical', 'At Risk', 'At Risk', 'Critical', 'Critical', 'At Risk', 'At Risk', 'At Risk', 'Critical', 'Critical', 'At Risk', 'At Risk', 'At Risk', 'At Risk', 'At Risk', 'At Risk', 'At Risk', 'At Risk', 'At Risk']
[[0.         0.00109299 0.99890701]
 [0.00429142 0.80303987 0.19266871]
 [0.01504849 0.66874276 0.31620876]]
